export { default as Home } from "./Home"
export { default as LeaderBoard } from "./LeaderBoard"
export { default as Profile } from "./Profile"
export { default as QuickSWap } from "./QuickSwap"
export {default as SkillMap} from "./SkillMap"